apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestcms
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: nestcms
  template:
    metadata:
      labels:
        app: nestcms
    spec:
      imagePullSecrets :
        - name : docker-secret # <-- your secret name here
      containers:
        - name: nestcms
          image: ghcr.io/abdoelhodaky/nestcmsimg:1.0.0 # Replace with your actual published image
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            # Add environment variables as needed
             - name: MONGO_URI
               valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_URI
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
