apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestcms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestcms
  template:
    metadata:
      labels:
        app: nestcms
    spec:
      imagePullSecrets :
        - name : docker-secret # <-- your secret name here
      containers:
        - name: nestcms
          image: abdoelhodaky/nestcms:latest # Replace with your actual published image
          ports:
            - containerPort: 3000
          env:
            # Add environment variables as needed
             - name: MONGO_URI
               value: "mongodb+srv://abdoarh36:TyWF4ABOefQhJFbP@cluster0.bc7sxu7.mongodb.net/nestcms"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
