apiVersion: v1
kind: Service
metadata:
  name: nestcms
spec:
  type: LoadBalancer
  selector:
    app: nestcms
  ports:
    - protocol: TCP
      port: 443
      targetPort: 3000
      nodePort: 30090  # You can change this to any available port in the 30000-32767 range if needed
