apiVersion: v1
kind: Service
metadata:
  name: nestcms-loadbalancer
  labels:
   service: ingress-controller
  annotations:
 # Example for AWS NLB with specific subnets
    service.beta.kubernetes.io/aws-load-balancer-internal: "true" # For internal load balancer
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-069d27f47d7e62de8,subnet-0b2694ce6b30df1d9,subnet-0c061308d068204dd"
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.2.50
  loadBalancerSourceRanges:
   - 192.168.2.0/24
  type: LoadBalancer
  selector:
    app: nestcms-loadbancl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30090  # You can change this to any available port in the 30000-32767 range if needed
