{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name | default (printf "%s-secrets" (include "nestcms.fullname" .)) }}
  labels:
    {{- include "nestcms.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.mongodb.enabled }}
  MONGO_URI: {{ include "nestcms.mongodbUri" . | b64enc }}
  {{- else if .Values.secrets.data.MONGO_URI }}
  MONGO_URI: {{ .Values.secrets.data.MONGO_URI | b64enc }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  REDIS_URI: {{ include "nestcms.redisUri" . | b64enc }}
  {{- end }}
  {{- if .Values.secrets.data.JWT_SECRET }}
  JWT_SECRET: {{ .Values.secrets.data.JWT_SECRET | b64enc }}
  {{- end }}
  {{- if .Values.secrets.data.PAYTABS_PROFILE_ID }}
  PAYTABS_PROFILE_ID: {{ .Values.secrets.data.PAYTABS_PROFILE_ID | b64enc }}
  {{- end }}
  {{- if .Values.secrets.data.PAYTABS_SERVER_KEY }}
  PAYTABS_SERVER_KEY: {{ .Values.secrets.data.PAYTABS_SERVER_KEY | b64enc }}
  {{- end }}
  {{- if .Values.secrets.data.PAYTABS_REGION }}
  PAYTABS_REGION: {{ .Values.secrets.data.PAYTABS_REGION | b64enc }}
  {{- end }}
{{- end }}

