---
# Source: nestcms/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubenestcms
  labels:
    helm.sh/chart: nestcms-0.1.0
    app.kubernetes.io/name: nestcms
    app.kubernetes.io/instance: kubenestcms
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
