name: kubetoolset

on:
  push:

env:
  ARKADE_BIN: " /home/runner/.arkade/bin"
  #KUBE_CONFILE: ${{secrets.KUBECONF}}


jobs:
  arkade:
     runs-on: ubuntu-latest
     steps:
        - 
           name: "setup arkade"
           uses: alexellis/setup-arkade@v1
        
        - 
           name: "arkade Init"
           uses: alexellis/arkade-get@master
           with:
            kubectl: latest
            helm: latest
            
  helm:
    runs-on: ubuntu-latest 
    needs:
       - arkade 
    steps:
       - 
        uses: actions/checkout@v4
       - 
        uses: isikerhan/setup-git@v1
        with:
          git-version: 2.44.3
      
       -
        run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
       
       -
        name: Check if directory exists
        id: check_dir
        run: |
          if  [ -d "nestcms" ]; then 
           echo "exists=true" >> "$GITHUB_OUTPUT"
          else
           echo "exists=false" >> "$GITHUB_OUTPUT"
          fi
       -
        name: " Helm stater plugin"
        if: ${{steps.check_dir.outputs.exists =='false' }}
        run : | 
             helm plugin install https://github.com/salesforce/helm-starter.git
             helm starter fetch https://github.com/christianknell/helm-starter.git
      
       -
        name : "Helm create chart for project"
        id: helm_chart_create
        if:  ${{steps.check_dir.outputs.exists =='false' }} 
        run : |
         helm create nestcms --starter helm-starter/default 
         echo "helm_chart_created=true" >> "$GITHUB_OUTPUT"
       -
        name : "Git Push"
        id: git_push
        if: ${{steps.helm_chart_create.outputs.helm_chart_created=='true' }}
        run : |
          cd nestcms
          git add . --all
          git commit -m " helm initialized" && git push
          


  deploy:
      runs-on: ubuntu-latest 
      needs:
         - helm
      steps:
        - uses: actions/checkout@v4
        - 
           id: changed-files
           uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c 

        - name: Run a step if my-file.txt was modified
          if: contains(steps.changed-files.outputs.modified_files, 'values.yaml')
          run: |
           helm install nestcms
