name: kubetoolset

on:
  push:

env:
  ARKADE_BIN: " /home/runner/.arkade/bin"


jobs:
  arkade:
     runs-on: ubuntu-latest
     steps:
        - 
           name: "setup arkade"
           uses: alexellis/setup-arkade@v1
        
        - 
           name: "arkade Init"
           uses: alexellis/arkade-get@master
           with:
            kubectl: latest
            helm: latest

  kube:
    runs-on: ubuntu-latest 
    needs:
       - arkade 
    steps:
    -
     name : "Helm check"
     run : |
         helm version
            

           
        
        

