name: kube

on:
  workflow_dispatch:

env:
  ARKADE_BIN: " /home/runner/.arkade/bin"
  KUBE_CONFILE: ${{secrets.KUBECONFIG}}
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  arkade:
     runs-on: ubuntu-latest
     steps:
        - 
           name: "setup arkade"
           uses: alexellis/setup-arkade@v1
        
        - 
           name: "arkade Init"
           uses: alexellis/arkade-get@master
           with:
            kubectl: latest
            helm: latest
            aws: latest 
            
#  kube_aws_confg:
#    runs-on: ubuntu-latest
   # needs:
#      - arkade 
 #   steps:
   #   - name: Setup AWS CLI
   #     run: |
    #      aws configure set aws_access_key_id ${{env.AWS_ACCESS_KEY_ID}}
     #     aws configure set aws_secret_access_key ${{env.AWS_SECRET_ACCESS_KEY}}

      
  #    - name: Set up Kubeconfig
    #    run: |
     #      echo "${{env.KUBE_CONFILE}}" > /tmp/kubeconfig.yaml
     #      chmod 775 /tmp/kubeconfig.yaml
     #
     #echo "KUBECONFIG=/tmp/kubeconfig.yaml" >> $GITHUB_ENV
  kubectl:
    runs-on: ubuntu-latest 
    needs:
       - arkade
    steps:
       - 
        uses: actions/checkout@v4
       - 
        uses: isikerhan/setup-git@v1
        with:
          git-version: 2.44.3
      
       -
        run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
         git pull
       -
        name: Check if directory exists
        id: check_dir
        run: |
          if  [ -d "nestcms" ]; then 
           echo "exists=true" >> "$GITHUB_OUTPUT"
          else
           echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

       -
        #name: " Helm template"
        if: ${{steps.check_dir.outputs.exists =='true' }}
        run : | 
             aws configure set aws_access_key_id ${{env.AWS_ACCESS_KEY_ID}}
             aws configure set aws_secret_access_key ${{env.AWS_SECRET_ACCESS_KEY}}
             echo "${{env.KUBE_CONFILE}}" > /tmp/kubeconfig.yaml
             chmod 775 /tmp/kubeconfig.yaml
             echo "KUBECONFIG=/tmp/kubeconfig.yaml" >> $GITHUB_ENV
             helm install nestcms-release oci://ghcr.io/abdoElHodaky/nestcms-v0.1.0.tgz
      
