name: kubetoolset

on:
  workflow_dispatch:



jobs:
  arkade:
     runs-on: ubuntu-latest
     steps:
        - 
           name: "setup arkade"
           uses: alexellis/setup-arkade@v1
        
        - 
           name: "arkade Init"
           uses: alexellis/arkade-get@master
           with:
            kubectl: latest
            helm: latest

        -
         name: "Arkade kubectl" 
         run : "echo /home/runner/.arkade/bin/helm --version"
        
            

           
        
        

