name: kubetoolset

on:
  push:
    branches:
     - master

env:
  ARKADE_BIN: " /home/runner/.arkade/bin"


jobs:
  arkade:
     runs-on: ubuntu-latest
     steps:
        - 
           name: "setup arkade"
           uses: alexellis/setup-arkade@v1
        
        - 
           name: "arkade Init"
           uses: alexellis/arkade-get@master
           with:
            kubectl: latest
            helm: latest
            git: latest

  helm:
    runs-on: ubuntu-latest 
    outputs:
       charts_dir:
         $
    needs:
       - arkade 
    steps:
    -
     name: " Helm stater plugin"
     run : | 
         helm plugin install https://github.com/salesforce/helm-starter.git
         
    -
     name : "Helm create chart for project"
     run : |
         helm starter fetch https://github.com/christianknell/helm-starter.git
         helm create nestcms --starter helm-starter/default 
        
    -
     name: "Push charts to Respo"
     run : | 
       cd nestcms
       git remote add helm_nestcms git@github.com:abdoElHodaky/Nestcms.git
       git add . -a 
       git config user.name github-actions
       git config user.email github-actions@github.com
       git commit -m "helm_chart" && git push helm_nestcms
       
       
       
      
