name: kubetoolset

on:
  push:
    branches:
     - master

env:
  ARKADE_BIN: " /home/runner/.arkade/bin"


jobs:
  arkade:
     runs-on: ubuntu-latest
     steps:
        - 
           name: "setup arkade"
           uses: alexellis/setup-arkade@v1
        
        - 
           name: "arkade Init"
           uses: alexellis/arkade-get@master
           with:
            kubectl: latest
            helm: latest

  helm:
    runs-on: ubuntu-latest 
    outputs:
       charts_dir:
         $
    needs:
       - arkade 
    steps:
    -
     name: " Helm stater plugin"
     run : | 
         helm plugin install https://github.com/salesforce/helm-starter.git
         
    -
     name : "Helm create chart for project"
     run : |
         helm starter fetch https://github.com/christianknell/helm-starter.git
         helm create nestcms --starter helm-starter/default 
         cd nestcms && echo "charts_dir=$PWD" >> $GITHUB_OUTPUT
  listdir:
     runs-on: ubuntu-latest
     needs:
      - helm 
     steps:
     -
       env:
        charts_dir:
          $GITHUB_OUTPUT
       run: |
        cd {$charts_dir} && ls -la
        
      
    





      
