name: kubetoolset

on:
  push:



jobs:
  arkade:
     runs-on: ubuntu-latest
     steps:
        - 
           name: "setup arkade"
           uses: alexellis/setup-arkade@v1
        
        - 
           name: "arkade Init"
           uses: alexellis/arkade-get@master
           with:
            kubectl: latest
            helm: latest

        -
         name: "Arkade kube" 
         run: |
          kubectl version
        
            

           
        
        

