name: kubetoolset

on:
  push:
    branches:
     - master

env:
  ARKADE_BIN: " /home/runner/.arkade/bin"


jobs:
  arkade:
     runs-on: ubuntu-latest
     steps:
        - 
           name: "setup arkade"
           uses: alexellis/setup-arkade@v1
        
        - 
           name: "arkade Init"
           uses: alexellis/arkade-get@master
           with:
            kubectl: latest
            helm: latest

  helm:
    runs-on: ubuntu-latest 
    needs:
       - arkade 
    steps:
    -
     name: " Helm stater plugin"
     run : | 
         helm plugin install https://github.com/salesforce/helm-starter.git
         
    -
     name : "Helm create chart for project"
     run : |
         helm starter fetch https://github.com/christianknell/helm-starter.git
         helm create nestcms --starter helm-starter/default 

         
  genIndex:
    runs-on: ubuntu-latest
    steps:
       -
        name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          
       - 
      
        uses: gacts/directory-listing@v1
        with:
          target: ./public
          # target: .
          # ignore: |
          #   build/**
          #   **/index.html
          #   node_modules/**,**/*.log
          # show-hidden: true
          # overwrite: true
