name: One-Time Push 

on:
  workflow_dispatch:

jobs:
  push-to-nest-next-copilot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip file
        run: |
          git config pull.rebase true 
          git fetch origin master 
          git reset --hard 822ad51
          git commit -m"reset"
          git push -f
