name: One-Time Push 

on:
 push:
  branches:
   - master

jobs:
  push-to-nest-next-copilot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip file
        run: |
          git reset --help
          git reset --hard 822ad5162faa9bf472bbf65825ea1b0a5b34c9cf
          git commit -m"reset"
          git push  -f
