name: One-Time Push 

on:
  workflow_dispatch:

jobs:
  push-to-nest-next-copilot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip file
        run: |
          git config pull.rebase true 
          git pull origin master 
          git checkout 822ad51 
          
      -  name: Commit and Push
         uses: GuillaumeFalourd/git-commit-push@v1.3
         with:
          commit_message: "Automated commit from GitHub Action"
          target_branch: ${{github.ref}}
          access_token: ${{ secrets.GITHUB_TOKEN }}
