name: One-Time Push 

on:
 push:
  branches:
   - master

jobs:
  push-to-nest-next-copilot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip file
        run: |
          git checkout 822ad51 -- src/**.ts
          git commit -m"reset"
          git push  -f
