name: One-Time Push 

on:
  workflow_dispatch:

jobs:
  push-to-nest-next-copilot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip file
        run: |
          #git config pull.rebase true
          git pull
          ls -la
          tar -xazvf kcert-1.0.7.tgz -C ./nestcms/cert
          
      -  name: Commit and Push
         uses: GuillaumeFalourd/git-commit-push@v1.3
         with:
          commit_message: "Automated commit from GitHub Action"
          target_branch: ${{github.ref}}
          access_token: ${{ secrets.GITHUB_TOKEN }}
