name: One-Time Push 

on:
 push:
  - master

jobs:
  push-to-nest-next-copilot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip file
        run: |
          git reset --hard 822ad51
          git commit -m"reset"
          git push origin master -f
